### ISSUE TITLE
bug: authentication token not provided error on npm i

### ISSUE THREAD

**Issue by fabus961** [robingenz/capacitor-plugin-demo#788]
**Describe the bug**
``` bash
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@5.3.1: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@capawesome-team/capacitor-file-opener/0.0.1/f131d9e19a577a22bbe19f357532345beb180b08 - authentication token not provided
```

**To Reproduce**

1. Git clone repo
2. cd into repo
3. npm i
5. ¯\_(ツ)_/¯

**Expected behavior**
The dependencies should install without authentication token not provided exception

**Desktop (please complete the following information):**

- OS: mac OS ventura 13.1
- Shell: zsh
- npm version 8.19.2

**Comment by robingenz** [comment]
Please have a look at the README: 
> You must have access to the Capawesome Sponsorware (Read more)

**Comment by gerhardcit** [comment]
> Please have a look at the README:
> 
> > You must have access to the Capawesome Sponsorware (Read more)
This points to an archived project? Any change of getting it updated?

https://github.com/capawesome-team/capacitor-datetime-picker#sponsorware

**Comment by robingenz** [comment]
I updated the README.md
