### ISSUE TITLE
bug: not installed, "npm i" failed

### ISSUE THREAD

**Issue by CBEPX** [robingenz/capacitor-plugin-demo#800]
subj

npm i ->
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@capawesome-team/capacitor-printer/5.1.0/93d8ef970ca2e5189c6f72c78f036bdd7a31fe0e - authentication token not provided

**Comment by robingenz** [comment]
Please take a look at the [README.md](https://github.com/robingenz/capacitor-plugin-demo?tab=readme-ov-file#prerequisites):

> You must have access to the Capawesome Sponsorware ([Read more](https://capawesome.io/insiders/))
